playground/core/urls.py
from django.urls import path
#from . import views
from .views import HomePageView, SamplePageviews

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('sample/', SamplePageviews.as_view(), name="sample"),
]

playground/pages/urls.py
from django.urls import path
#from . import views
from .views import PageListView, PageDetailView, PageCreate, PageUpdate, PageDelete

app_name = "pages"

urlpatterns = [
    path('', PageListView.as_view(), name='pages'),
    path('<int:pk>/<slug:page_slug>/', PageDetailView.as_view(), name='page'),
    path('create/', PageCreate.as_view(), name = 'create'),
    path('update/<int:pk>/', PageUpdate.as_view(), name = 'update'),
    path('delete/<int:pk>/', PageDelete.as_view(), name = "delete")
]

playground/playground/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    path('pages/', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('profiles/', include('profiles.urls')),
    #Paths de Auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    path('messenger/', include('messenger.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

playground/pages/models.py
from django.db import models
from ckeditor.fields import RichTextField

class Page(models.Model):
    title = models.CharField(verbose_name="Título", max_length=200)
    content = RichTextField(verbose_name="Contenido")
    order = models.SmallIntegerField(verbose_name="Orden", default=0)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "página"
        verbose_name_plural = "páginas"
        ordering = ['order', 'title']

    def __str__(self):
        return self.title

playground/pages/templates/pages/page.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}{{page.title}}{% endblock %}
{% block content %}
{% include 'pages/includes/pages_menu.html' %}
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <h2 class="section-heading mb-4">{{page.title}}</h2>
        <div>
          {{page.content|safe}}
          {% if request.user.is_staff %}
            <p><a href="{% url 'pages:update' page.id %}">Editar</a></p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

playground/pages/templates/pages/page_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Borrar página{% endblock %}
{% block content %}
{% include 'pages/includes/pages_menu.html'%}
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
            <form action="" method="post">{% csrf_token %}
                <p>¿Estás seguro de que quieres borrar <b>"{{ object }}"</b>?</p>
                <input type="submit" value="Si, borrar la página" class="btn btn-primary btn-block" />
            </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

playground/pages/templates/pages/page_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Crear página{% endblock %}
{% block content %}
{% include 'pages/includes/pages_menu.html'%}
<main role="main">
  <div class="container">
    <div class="row mt-3 mb-5">
      <div class="col-md-9 mx-auto">
        <form action="" method="post">{% csrf_token %}
                {{ form.as_p }}
            <div class="text-center">
              <input type="submit" value="Crear página" class="btn btn-primary btn-block" />
            </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock %}

playground/pages/templates/pages/page_update_form.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Actualizar página{% endblock %}
{% block content %}
{% include 'pages/includes/pages_menu.html'%}
<main role="main">
  <div class="container">
    <div class="row mt-3 mb-5">
      <div class="col-md-9 mx-auto">
        <div>
          {% if 'ok' in request.GET %}
            <p style="color: green;">Página editada correctamente
              <a href="{% url 'pages:page' page.id page.title|slugify %}">Haz clic aquí para ver el resultado</a>
            </p>
          {% endif %}
          <form action="" method="post">{% csrf_token %}
                  {{ form.as_p }}
              <div class="text-center">
                <input type="submit" value="Crear página" class="btn btn-primary btn-block" />
              </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

playground/pages/templates/pages/pages.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Páginas{% endblock %}
{% block content %}
{% include 'pages/includes/pages_menu.html' %}
<main role="main">
  <div class="container mb-4">
    {% for page in page_list|dictsort:"id" reversed %}
      <div class="row mt-3">
        <div class="col-md-9 mx-auto">
          <h2 class="mb-4">{{page.title}}</h2>
          <div>
            <p>{{page.content|striptags|safe|truncatechars:"200"}}</p>
            <p><a href="{% url 'pages:page' page.id page.title|slugify %}">Leer más</a>

              {% if request.user.is_staff %}
                | <a href="{% url 'pages:update' page.id %}">Editar</a>
                | <a href="{% url 'pages:delete' page.id %}">Borrar</a>
              {% endif %}
            </p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</main>
{% endblock %}