playground/core/urls.py
from django.urls import path
#from . import views
from .views import HomePageView, SamplePageviews

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('sample/', SamplePageviews.as_view(), name="sample"),
]

playground/messenger/urls.py
from django.urls import path
from .views import ThreadList, ThreadDetail, add_message, start_thread

app_name = "messenger"

urlpatterns = [
    path('', ThreadList.as_view(), name='list'),
    path('thread/<int:pk>/', ThreadDetail.as_view(), name="detail"),
    path('thread/<int:pk>/add', add_message, name="add"),
    path('thread/start/<username>', start_thread, name="start"),
]

playground/playground/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    path('pages/', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('profiles/', include('profiles.urls')),
    #Paths de Auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    path('messenger/', include('messenger.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

playground/profiles/urls.py
from django.urls import path
from .views import ProfileListView, ProfileDetailView

app_name = "profiles"

urlpatterns = [
        path('', ProfileListView.as_view(), name='list'),
        path('<username>/', ProfileDetailView.as_view(), name='detail'),
]

playground/messenger/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import m2m_changed

# Create your models here.
class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created']

class ThreadManager(models.Manager):
    def find(self, user1, user2):
        #self = Thread.objects (cunado es un model.Manager)
        queryset = self.filter(users=user1).filter(users=user2)
        if len(queryset) > 0:
            return queryset[0]
        return None

    def find_or_create(self, user1, user2):
        thread = self.find(user1, user2)
        if thread is None:
            thread = Thread.objects.create()
            thread.users.add(user1, user2)
        return thread

class Thread(models.Model):
    users = models.ManyToManyField(User, related_name='threads')
    messages = models.ManyToManyField(Message)
    # Los campos ManyToMany no afectan directamente al updated, se gestionan aparte. De forma manual se debe forzar el guardado para que se almacene la fecha de modificación
    updated = models.DateTimeField(auto_now = True)

    objects = ThreadManager()

    class Meta:
        ordering = ['-updated']


def messages_changed(sender, **kwargs):
    #Instancia que manda la señal (el hilo al que se trata de de añadir los mensajes)
    instance = kwargs.pop("instance", None)
    #Acción que se está ejecutando (pre_add: momento justo antes de añadir los mensajes, post_add)
    action = kwargs.pop("action", None)
    #Refernencia a un conjunto que almacena los identificadores de todos los mensajes que se van a añadir dentro de la relacion ManyToMany
    pk_set = kwargs.pop("pk_set", None)
    print(instance, action, pk_set)

    false_pk_set = set()
    if action is "pre_add":
        for msg_pk in pk_set:
            msg = Message.objects.get(pk=msg_pk)
            if msg.user not in instance.users.all():
                print("Ups, ({}) no forma parte del hilo".format(msg.user))
                false_pk_set.add(msg_pk)
    #Buscar los mensajes de false_pk_set que si estan en pk_set y los borramos de pk_set
    pk_set.difference_update(false_pk_set)

    #Forzar la actualización haciendo un save
    instance.save()

m2m_changed.connect(messages_changed, sender = Thread.messages.through)

playground/messenger/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Thread, Message
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import Http404, JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.models import User
from django.urls import reverse_lazy

# Create your views here.
@method_decorator(login_required, name="dispatch")
class ThreadList(TemplateView):
    template_name = "messenger/thread_list.html"

@method_decorator(login_required, name="dispatch")
class ThreadDetail(DetailView):
    model = Thread

    def get_object(self):
        obj = super(ThreadDetail, self).get_object()
        if self.request.user not in obj.users.all():
            raise Http404()
        return obj

def add_message(request, pk):
    print(request.GET)
    json_response = {'created': False}
    if request.user.is_authenticated:
        content = request.GET.get('content', None)
        if content:
            thread = get_object_or_404(Thread, pk = pk)
            message = Message.objects.create(user = request.user, content = content)
            thread.messages.add(message)
            json_response['created'] = True
            if len(thread.messages.all()) is 1:
                json_response['first'] = True
    else:
        raise Http404("User is not authenticated")
    return JsonResponse(json_response)

@login_required
def start_thread(request, username):
    user = get_object_or_404(User, username=username)
    thread = Thread.objects.find_or_create(user, request.user)
    return redirect(reverse_lazy('messenger:detail', args = [thread.pk]))

playground/messenger/templates/messenger/thread_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Hilo{% endblock %}
{% block content %}
<style>
  .avatar  { width:50px; height:50px; float:left; margin-right:10px; }
  .thread  { max-height:300px; overflow-y:auto; padding:0 0.5em;}
  .mine    { padding:0 0.5em 0.25em; background-color:rgba(230,242,245,.5); width:92%; margin-left:8%; }
  .other   { padding:0 0.5em 0.25em; background-color:#f2f3f5; width:92%; }
</style>
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto mb-5">
        <div class="row">
          <!-- Hilos de conversación -->
          <div class="col-md-4">
            <!-- Con una búsqueda inversa user.threads también podemos conseguir los hilos de un usuario -->
            {% for thread in request.user.threads.all %}
              <!-- Sólo mostraremos un Thread si tiene como mínimo 1 mensaje -->
              {% if thread.messages.all|length > 0 %}
                <div class="mb-3">
                  <!-- Recorremos los miembros del hilo menos el propio request.user -->
                  {% for user in thread.users.all %}
                    {% if user != request.user %}
                      <!-- Mostramos el avatar del miembro -->
                      {% if user.profile.avatar %}
                        <img src="{{user.profile.avatar.url}}" class="avatar">
                      {% else %}
                        <img src="{% static 'registration/img/no-avatar.jpg' %}" class="avatar">
                      {% endif %}
                      <!-- Mostramos la información del miembro -->
                      <div>
                        <a href="{% url 'messenger:detail' thread.pk %}">{{user}}</a><br>
                        <small><i>Hace {{thread.messages.last.created|timesince}}</i></small>
                      </div>
                    {% endif %}
                  {% endfor %}
                </div>
              {% endif %}
            {% endfor %}
          </div>
          <!-- Hilo de conversación -->
          <div class="col-md-8">
            <!-- Recorremos los miembros del hilo menos el propio request.user -->
            {% for user in thread.users.all %}
              {% if user != request.user %}
                <h4 class="mb-4">Mensajes con <a href="{% url 'profiles:detail' user %} ">{{user}}</a></h4>
              {% endif %}
            {% endfor %}
            <!-- Mostramos los mensajes en una capa que tiene un overflow vertical de 300 píxeles -->
            <div class="thread" id="thread">
              {% for message in object.messages.all %}
                <!-- Dependiendo del usuario asignamos una clase con un color de fondo u otro en el mensaje -->
                <div {% if request.user == message.user %}class="mine mb-3"{% else %}class="other mb-3"{% endif %}>
                  <small><i>Hace {{thread.messages.last.created|timesince}}</i></small><br>
                  {{message.content}}
                </div>
              {% endfor %}
            </div>
            <!-- Aquí crearemos el formulario -->
            <textarea id="content" class="form-control mb-2" rows="2" placeholder="Escribe tu mensaje aquí"></textarea>
            <button id="send" class="btn btn-primary btn-sm btn-block" disabled >Enviar mensaje</button>
            <script type="text/javascript">
              var send = document.getElementById("send");
              send.addEventListener("click", function(){
                var content = encodeURIComponent(document.getElementById("content").value);
                if (content.length > 0){
                  document.getElementById("content").value = '';
                  send.disabled = true;
                  const url = "{% url 'messenger:add' thread.pk %}" + "?content=" + content;
                  fetch(url, {'credentials': 'include'}).then(response => response.json()).then(function(data){
                    // Si el mensaje se ha creado correctamente...
                    if (data.created){
                       // Aquí iría el código de creación del mensaje dinámicamente
                       var message = document.createElement('div');
                       message.classList.add('mine', 'mb-3');
                       message.innerHTML = '<small><i>Hace unos segundos</i></small><br>'+ decodeURIComponent(content);
                       document.getElementById('thread').appendChild(message);
                       ScrollBottomInThread();
                    }else{
                      // Si algo ha ido mal podemos debugear en la consola del inspector
                      console.log("Algo ha fallado y el mensaje no se ha podido añadir.");
                    }
                  })
                }
              })

              //Evento que activa o desactiva el botón dependiendo de si hay o no mensaje
              var content = document.getElementById("content");
              content.addEventListener("keyup", function(){
                if (!this.checkValidity() || !this.value){
                  send.disabled = true;
                }else{
                  send.disabled = false;
                }
              })

              // Forzar el Scroll abajo del todo
              function ScrollBottomInThread(){
                var thread = document.getElementById("thread");
                thread.scrollTop = thread.scrollHeight;
              }

              ScrollBottomInThread();
              //Si es le primer mensaje del hilo actualizaremos para que aparezca a la izquierda
              if(data.first){
                window.location.href = "{% url 'messenger:detail' thread.pk %}"
              }
            </script>
          </div>
        </div>
    </div>
  </div>
</main>
{% endblock %}

playground/messenger/templates/messenger/thread_list.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Mensajes{% endblock %}
{% block content %}
<style>
  .avatar  { width:50px; height:50px; float:left; margin-right:10px; }
</style>
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto mb-5">
        <div class="row">
          <!-- Hilos de conversación -->
          <div class="col-md-4">
            <!-- Recorremos los Threads y sólo mostramos los que tienen como mínimo 1 mensaje -->
            {% for thread in request.user.threads.all %}
              {% if thread.messages.all|length > 0 %}
                <div class="mb-3">
                  <!-- Recorremos los miembros del hilo menos el propio request.user -->
                  {% for user in thread.users.all %}
                    {% if user != request.user %}   
                      <!-- Mostramos el avatar del miembro -->  
                      {% if user.profile.avatar %}
                        <img src="{{user.profile.avatar.url}}" class="avatar">
                      {% else %}
                        <img src="{% static 'registration/img/no-avatar.jpg' %}" class="avatar">
                      {% endif %}
                      <!-- Mostramos la información del miembro -->
                      <div>
                        <a href="{% url 'messenger:detail' thread.pk %}">{{user}}</a><br>
                        <small><i>Hace {{thread.messages.last.created|timesince}}</i></small>
                      </div>
                    {% endif %}
                  {% endfor %}
                </div>
              {% endif %}
            {% endfor %}
          </div>
          <!-- Hilos de conversación -->
          <div class="col-md-8">
            <p><i>Selecciona un hilo de conversación de tu panel izquierdo.</i></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}