playground/core/urls.py
from django.urls import path
#from . import views
from .views import HomePageView, SamplePageviews

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('sample/', SamplePageviews.as_view(), name="sample"),
]

playground/pages/urls.py
from django.urls import path
#from . import views
from .views import PageListView, PageDetailView, PageCreate, PageUpdate, PageDelete

app_name = "pages"

urlpatterns = [
    path('', PageListView.as_view(), name='pages'),
    path('<int:pk>/<slug:page_slug>/', PageDetailView.as_view(), name='page'),
    path('create/', PageCreate.as_view(), name = 'create'),
    path('update/<int:pk>/', PageUpdate.as_view(), name = 'update'),
    path('delete/<int:pk>/', PageDelete.as_view(), name = "delete")
]

playground/playground/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    path('pages/', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('profiles/', include('profiles.urls')),
    #Paths de Auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    path('messenger/', include('messenger.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

playground/pages/templates/pages/includes/pages_menu.html
{% load static %}
<link rel="stylesheet" href="{% static 'pages/css/custom_ckeditor.css' %}">
<script type="text/javascript" src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>

{% if request.user.is_staff %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <span class="navbar-brand" href="#"><i>Administrar</i></span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nep" aria-controls="nep" aria-expanded="false">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nep">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:create' %}"><i>Crear página</i></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pages:pages' %}"><i>Listar páginas</i></a>
        </li>
      </ul>
    </div>
  </div>
</nav>
{% endif %}