playground/core/urls.py
from django.urls import path
#from . import views
from .views import HomePageView, SamplePageviews

urlpatterns = [
    path('', HomePageView.as_view(), name="home"),
    path('sample/', SamplePageviews.as_view(), name="sample"),
]

playground/messenger/urls.py
from django.urls import path
from .views import ThreadList, ThreadDetail, add_message, start_thread

app_name = "messenger"

urlpatterns = [
    path('', ThreadList.as_view(), name='list'),
    path('thread/<int:pk>/', ThreadDetail.as_view(), name="detail"),
    path('thread/<int:pk>/add', add_message, name="add"),
    path('thread/start/<username>', start_thread, name="start"),
]

playground/pages/urls.py
from django.urls import path
#from . import views
from .views import PageListView, PageDetailView, PageCreate, PageUpdate, PageDelete

app_name = "pages"

urlpatterns = [
    path('', PageListView.as_view(), name='pages'),
    path('<int:pk>/<slug:page_slug>/', PageDetailView.as_view(), name='page'),
    path('create/', PageCreate.as_view(), name = 'create'),
    path('update/<int:pk>/', PageUpdate.as_view(), name = 'update'),
    path('delete/<int:pk>/', PageDelete.as_view(), name = "delete")
]

playground/playground/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    path('pages/', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('profiles/', include('profiles.urls')),
    #Paths de Auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    path('messenger/', include('messenger.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

playground/profiles/urls.py
from django.urls import path
from .views import ProfileListView, ProfileDetailView

app_name = "profiles"

urlpatterns = [
        path('', ProfileListView.as_view(), name='list'),
        path('<username>/', ProfileDetailView.as_view(), name='detail'),
]

playground/core/models.py
from django.db import models

# Create your models here.

playground/core/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView

#def home(request):
#    return render(request, "core/home.html")
#
#def sample(request):
#    return render(request, "core/sample.html")

class HomePageView(TemplateView):
    template_name = "core/home.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'title': 'Mi super web Playground'})

class SamplePageviews(TemplateView):
    template_name = "core/sample.html"

playground/core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <!-- Fuentes -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,700,700i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    <!-- Estilos -->
    <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'core/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'core/css/main.css' %}" rel="stylesheet">
  </head>
  <body>
    <body>
      <!-- Navegación -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}">Playground</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ned" aria-controls="ned" aria-expanded="false">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="ned">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Inicio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'pages:pages' %}">Páginas</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'profiles:list' %}">Perfiles</a>
              </li>
            </ul>
            <ul class="navbar-nav">
              {% if not request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'login' %}">Acceder</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'signup' %}">Registro</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'profile' %}">Perfil</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'messenger:list' %}">Mensajes</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'logout' %}">Salir</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      <!-- Contenido -->
      {% block content %}{% endblock %}
      <!-- Javascript -->
      <script src="{% static 'core/vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'core/js/main.js' %}"></script>
  </body>
</html>

playground/core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Inicio{% endblock %}
{% block content %}
<div class="container">
  <div style="padding-top:50px; text-align:center;">
    <h1>{{ title }}</h1>
    <p class="lead">CBV, autenticación, registros, perfiles y más</p>
  </div>
</div>
{% endblock %}

playground/core/templates/core/sample.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Página{% endblock %}
{% block content %}
<main role="main">
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-md-3">
        <img src="{% static 'core/img/placeholder.png' %}" class="img-fluid"/>
      </div>
      <div class="col-md-6 mt-3">
        <h3>Página de prueba</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce hendrerit nibh vel faucibus auctor. 
          Phasellus non arcu dictum, porttitor orci sed, maximus ligula. Duis mollis pulvinar tempor. 
          Cras ex nisl, fringilla ut rhoncus a, vestibulum ac turpis.</p>
      </div>
    </div>
  </div>
</main>
{% endblock %}